version: "3.8"
services:
  carbon-redis:
    image: redis:7.0-alpine
    restart: always
    ports:
      - "6389:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
